apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todolist
  name: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todolist
    spec:
      containers:
      - image: us.gcr.io/todolist-302506/todolist
        name: todolist
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: DB_HOST
          value: postgres.todolist.svc
        readinessProbe:
          httpGet:
            path: /api/actuator
            port: 8080
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /api/actuator
            port: 8080
            scheme: HTTP
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
status: {}