apiVersion: v1
kind: Service
metadata:
  labels:
    app: todolist
  name: todolist
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todolist
  sessionAffinity: None
  type: ClusterIP