"""empty message

Revision ID: 40451f7e5152
Revises: 
Create Date: 2021-01-25 20:30:48.481921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40451f7e5152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todolist')
    # ### end Alembic commands ###
